import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "@/components/mainBackground/Navbar";
import getUser from "@/actions/nextAuthActions/getUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const user=await getUser()

  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-900 overflow-x-hidden`}>
      <Toaster
  position="top-center"
  reverseOrder={false}
/>
{/* <Navbar user={user}/>  */}
    {children}
       
        </body>
    </html>
  );
}
